stages:
  - deploy

job_deploy_master:
  stage: deploy
  only:
    - master
  script:
    - |
      bash ssh -t -t -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' -o 'PubkeyAuthentication yes' -i '/home/gitlab_ci_multi_runner/.ssh/ansibleagent.key' ansibleagent@ws-prod-monitor-01.lanecc.edu <<EOF
        bash cd /etc/ansible/roles/lanebook
        bash git fetch origin
        bash git reset --hard origin/master
        bash git submodule update --init
        bash exit
      bash EOF
  tags:
    - ansible
